"""Aditya Hridayam and Vishnu Sahasranama — selected verses with five-language meanings.

Source texts are traditional Sanskrit and in the public domain.
Aditya Hridayam appears in the Yuddha Kanda of the Valmiki Ramayana.
Vishnu Sahasranama appears in the Anushasana Parva of the Mahabharata.

These are curated selections, not the complete texts, and the meanings are simplified
study explanations rather than scholarly translations.
"""

# (number, devanagari, transliteration, {lang: meaning})
_ADITYA = [
    (1,
     "ततो युद्धपरिश्रान्तं समरे चिन्तया स्थितम्।\nरावणं चाग्रतो दृष्ट्वा युद्धाय समुपस्थितम्॥",
     "Tato yuddha-parishraantam samare chintayaa sthitam.\nRaavanam chaagrato drishtvaa yuddhaaya samupasthitam.",
     {"en": "Rama, exhausted by battle and lost in thought, saw Ravana standing ready before him.",
      "hi": "युद्ध से थके और चिंता में खड़े राम ने सामने रावण को युद्ध के लिए तैयार देखा।",
      "te": "యుద్ధంతో అలసిపోయి, ఆలోచనలో నిలిచిన రాముడు ఎదురుగా యుద్ధానికి సిద్ధమైన రావణుని చూశాడు.",
      "ta": "போரால் களைத்து, சிந்தனையில் நின்ற ராமன், முன்னே போருக்குத் தயாராக நின்ற ராவணனைக் கண்டான்.",
      "kn": "ಯುದ್ಧದಿಂದ ಬಳಲಿ, ಚಿಂತೆಯಲ್ಲಿ ನಿಂತ ರಾಮನು ಮುಂದೆ ಯುದ್ಧಕ್ಕೆ ಸಿದ್ಧನಾದ ರಾವಣನನ್ನು ಕಂಡನು."}),
    (2,
     "दैवतैश्च समागम्य द्रष्टुमभ्यागतो रणम्।\nउपागम्याब्रवीद्राममगस्त्यो भगवान् ऋषिः॥",
     "Daivataish cha samaagamya drashtum abhyaagato ranam.\nUpaagamyaabraveed Raamam Agastyo bhagavaan rishih.",
     {"en": "The sage Agastya, who had come with the gods to witness the battle, approached Rama and spoke.",
      "hi": "देवताओं के साथ युद्ध देखने आए भगवान अगस्त्य ऋषि राम के पास आकर बोले।",
      "te": "దేవతలతో కలిసి యుద్ధం చూడ వచ్చిన అగస్త్య మహర్షి రాముని దగ్గరకు వచ్చి పలికాడు.",
      "ta": "தேவர்களுடன் போரைக் காண வந்த அகத்திய முனிவர் ராமனை அணுகிக் கூறினார்.",
      "kn": "ದೇವತೆಗಳೊಂದಿಗೆ ಯುದ್ಧ ನೋಡಲು ಬಂದ ಅಗಸ್ತ್ಯ ಮಹರ್ಷಿ ರಾಮನ ಬಳಿ ಬಂದು ಹೇಳಿದರು."}),
    (3,
     "राम राम महाबाहो शृणु गुह्यं सनातनम्।\nयेन सर्वानरीन् वत्स समरे विजयिष्यसे॥",
     "Raama Raama mahaabaaho shrinu guhyam sanaatanam.\nYena sarvaan areen vatsa samare vijayishyase.",
     {"en": "O mighty-armed Rama, hear this timeless secret by which, dear child, you will prevail over every adversary in battle.",
      "hi": "हे महाबाहु राम, यह सनातन गुह्य सुनो, जिससे हे वत्स, तुम युद्ध में सब शत्रुओं पर विजय पाओगे।",
      "te": "ఓ మహాబాహు రామా, ఈ సనాతన రహస్యాన్ని విను; దీనితో నాయనా, యుద్ధంలో సర్వ శత్రువులను జయిస్తావు.",
      "ta": "பெருந்தோள் ராமனே, இந்த நித்திய இரகசியத்தைக் கேள்; இதனால் மகனே, போரில் எல்லா எதிரிகளையும் வெல்வாய்.",
      "kn": "ಓ ಮಹಾಬಾಹು ರಾಮ, ಈ ಸನಾತನ ಗುಹ್ಯವನ್ನು ಕೇಳು; ಇದರಿಂದ ಮಗು, ಯುದ್ಧದಲ್ಲಿ ಎಲ್ಲ ಶತ್ರುಗಳನ್ನು ಜಯಿಸುವೆ."}),
    (4,
     "आदित्यहृदयं पुण्यं सर्वशत्रुविनाशनम्।\nजयावहं जपेन्नित्यमक्षय्यं परमं शिवम्॥",
     "Aaditya-hridayam punyam sarva-shatru-vinaashanam.\nJayaavaham japen nityam akshayyam paramam shivam.",
     {"en": "This is the sacred Aditya Hridayam, which the tradition holds to destroy all enmity and bring victory; recite it daily as an imperishable and auspicious practice.",
      "hi": "यह पवित्र आदित्यहृदय सब शत्रुओं का नाश करने वाला और विजय देने वाला माना जाता है; इसे नित्य जपो, यह अक्षय और परम शिव है।",
      "te": "ఇది పవిత్ర ఆదిత్య హృదయం; సర్వ శత్రు నాశనం, జయప్రదం అని సంప్రదాయం చెబుతుంది; నిత్యం జపించు, ఇది అక్షయం, పరమ శుభం.",
      "ta": "இது புனித ஆதித்ய ஹ்ருதயம்; எல்லா பகையையும் அழித்து வெற்றி தரும் என்பது பாரம்பரியம்; நாளும் ஓது, இது அழியாத, மிக மங்கலமானது.",
      "kn": "ಇದು ಪವಿತ್ರ ಆದಿತ್ಯ ಹೃದಯ; ಸರ್ವ ಶತ್ರು ನಾಶಕ, ಜಯಪ್ರದ ಎಂದು ಸಂಪ್ರದಾಯ ಹೇಳುತ್ತದೆ; ನಿತ್ಯ ಜಪಿಸು, ಇದು ಅಕ್ಷಯ ಮತ್ತು ಪರಮ ಶುಭ."}),
    (5,
     "सर्वमङ्गलमाङ्गल्यं सर्वपापप्रणाशनम्।\nचिन्ताशोकप्रशमनमायुर्वर्धनमुत्तमम्॥",
     "Sarva-mangala-maangalyam sarva-paapa-pranaashanam.\nChintaa-shoka-prashamanam aayur-vardhanam uttamam.",
     {"en": "It is called the most auspicious of all auspicious things, said to remove wrongdoing, calm anxiety and sorrow, and lengthen life.",
      "hi": "यह सब मंगलों में मंगल है, पापों का नाश करने वाला, चिंता-शोक शांत करने वाला और आयु बढ़ाने वाला उत्तम स्तोत्र है।",
      "te": "ఇది సర్వ మంగళాలలో మంగళం; పాపనాశకం, చింత శోకాలను శమింపజేసేది, ఆయువును పెంచే ఉత్తమమైనది.",
      "ta": "இது எல்லா மங்கலங்களிலும் மங்கலம்; பாவம் நீக்கி, கவலையையும் துயரையும் தணித்து, ஆயுளை நீட்டிக்கும் உயர்ந்தது.",
      "kn": "ಇದು ಸರ್ವ ಮಂಗಳಗಳಲ್ಲಿ ಮಂಗಳ; ಪಾಪನಾಶಕ, ಚಿಂತೆ ಶೋಕವನ್ನು ಶಮನ ಮಾಡುವ, ಆಯುಷ್ಯ ಹೆಚ್ಚಿಸುವ ಉತ್ತಮವಾದದ್ದು."}),
    (6,
     "रश्मिमन्तं समुद्यन्तं देवासुरनमस्कृतम्।\nपूजयस्व विवस्वन्तं भास्करं भुवनेश्वरम्॥",
     "Rashmimantam samudyantam devaasura-namaskritam.\nPoojayasva vivasvantam bhaaskaram bhuvaneshvaram.",
     {"en": "Worship the rising sun, radiant with rays, honoured by gods and asuras alike, the light-maker and lord of the worlds.",
      "hi": "किरणों से युक्त, उदय होते हुए, देव-असुरों से नमस्कृत विवस्वान भास्कर भुवनेश्वर की पूजा करो।",
      "te": "కిరణాలతో ప్రకాశించే, ఉదయించే, దేవాసురులచే నమస్కరించబడిన వివస్వంతుడైన భాస్కర భువనేశ్వరుని పూజించు.",
      "ta": "கதிர்களுடன் ஒளிரும், உதயமாகும், தேவர் அசுரர் வணங்கும் விவஸ்வானாகிய பாஸ்கர புவனேஸ்வரனை வணங்கு.",
      "kn": "ಕಿರಣಗಳಿಂದ ಬೆಳಗುವ, ಉದಯಿಸುವ, ದೇವಾಸುರರಿಂದ ನಮಸ್ಕೃತನಾದ ವಿವಸ್ವಂತ ಭಾಸ್ಕರ ಭುವನೇಶ್ವರನನ್ನು ಪೂಜಿಸು."}),
    (7,
     "सर्वदेवात्मको ह्येष तेजस्वी रश्मिभावनः।\nएष देवासुरगणाँल्लोकान् पाति गभस्तिभिः॥",
     "Sarva-devaatmako hyesha tejasvee rashmi-bhaavanah.\nEsha devaasura-gaanaan lokaan paati gabhastibhih.",
     {"en": "He is the essence of all the shining ones, brilliant, the source of rays, and with his beams he sustains all the worlds and their beings.",
      "hi": "वे सब देवताओं के आत्मस्वरूप, तेजस्वी और किरणों के स्रोत हैं; अपनी किरणों से देव-असुर सहित सब लोकों का पालन करते हैं।",
      "te": "ఆయన సర్వ దేవతల ఆత్మస్వరూపుడు, తేజస్వి, కిరణాల మూలం; తన కిరణాలతో దేవాసురులతో సహా సర్వ లోకాలను పాలిస్తాడు.",
      "ta": "அவர் எல்லா தேவர்களின் ஆன்ம வடிவம், ஒளிமிக்கவர், கதிர்களின் மூலம்; தன் கதிர்களால் தேவர் அசுரர் உட்பட எல்லா உலகங்களையும் காக்கிறார்.",
      "kn": "ಅವನು ಸರ್ವ ದೇವತೆಗಳ ಆತ್ಮಸ್ವರೂಪ, ತೇಜಸ್ವಿ, ಕಿರಣಗಳ ಮೂಲ; ತನ್ನ ಕಿರಣಗಳಿಂದ ದೇವಾಸುರರೊಂದಿಗೆ ಎಲ್ಲ ಲೋಕಗಳನ್ನು ಪಾಲಿಸುತ್ತಾನೆ."}),
    (8,
     "एष ब्रह्मा च विष्णुश्च शिवः स्कन्दः प्रजापतिः।\nमहेन्द्रो धनदः कालो यमः सोमो ह्यपां पतिः॥",
     "Esha Brahmaa cha Vishnush cha Shivah Skandah Prajaapatih.\nMahendro dhanadah kaalo Yamah Somo hyapaam patih.",
     {"en": "He is spoken of as Brahma, Vishnu, Shiva, Skanda, Prajapati, Indra, Kubera, time itself, Yama, Soma and lord of the waters.",
      "hi": "वे ही ब्रह्मा, विष्णु, शिव, स्कंद, प्रजापति, महेंद्र, कुबेर, काल, यम, सोम और जल के स्वामी कहे जाते हैं।",
      "te": "ఆయనే బ్రహ్మ, విష్ణువు, శివుడు, స్కందుడు, ప్రజాపతి, మహేంద్రుడు, కుబేరుడు, కాలం, యముడు, సోముడు, జలాధిపతి అని చెప్పబడుతుంది.",
      "ta": "அவரே பிரம்மா, விஷ்ணு, சிவன், ஸ்கந்தன், பிரஜாபதி, இந்திரன், குபேரன், காலம், யமன், சோமன், நீரின் தலைவன் எனப்படுகிறார்.",
      "kn": "ಅವನೇ ಬ್ರಹ್ಮ, ವಿಷ್ಣು, ಶಿವ, ಸ್ಕಂದ, ಪ್ರಜಾಪತಿ, ಮಹೇಂದ್ರ, ಕುಬೇರ, ಕಾಲ, ಯಮ, ಸೋಮ, ಜಲಾಧಿಪತಿ ಎಂದು ಹೇಳಲಾಗುತ್ತದೆ."}),
    (9,
     "नमः पूर्वाय गिरये पश्चिमायाद्रये नमः।\nज्योतिर्गणानां पतये दिनाधिपतये नमः॥",
     "Namah poorvaaya giraye pashchimaayaadraye namah.\nJyotir-gaanaanaam pataye dinaadhipataye namah.",
     {"en": "Salutations to the eastern mountain of his rising and the western mountain of his setting, to the lord of all lights and the ruler of the day.",
      "hi": "उदय के पूर्व पर्वत और अस्त के पश्चिम पर्वत को नमस्कार; ज्योतियों के स्वामी और दिन के अधिपति को नमस्कार।",
      "te": "ఉదయ పూర్వ పర్వతానికి, అస్తమయ పశ్చిమ పర్వతానికి నమస్కారం; జ్యోతుల అధిపతికి, దినాధిపతికి నమస్కారం.",
      "ta": "உதயத்தின் கிழக்கு மலைக்கும், மறைவின் மேற்கு மலைக்கும் வணக்கம்; ஒளிகளின் தலைவனுக்கும் பகலின் அதிபதிக்கும் வணக்கம்.",
      "kn": "ಉದಯದ ಪೂರ್ವ ಪರ್ವತಕ್ಕೆ, ಅಸ್ತಮಯದ ಪಶ್ಚಿಮ ಪರ್ವತಕ್ಕೆ ನಮಸ್ಕಾರ; ಜ್ಯೋತಿಗಳ ಒಡೆಯನಿಗೆ, ದಿನಾಧಿಪತಿಗೆ ನಮಸ್ಕಾರ."}),
    (10,
     "अस्मिन् क्षणे महाबाहो रावणं त्वं वधिष्यसि।\nएवमुक्त्वा तदागस्त्यो जगाम स यथागतम्॥",
     "Asmin kshane mahaabaaho Raavanam tvam vadhishyasi.\nEvam uktvaa tadaa Agastyo jagaama sa yathaagatam.",
     {"en": "'In this very moment, mighty-armed one, you will overcome Ravana.' Having said this, Agastya departed as he had come.",
      "hi": "'हे महाबाहु, इसी क्षण तुम रावण का वध करोगे।' यह कहकर अगस्त्य जैसे आए थे वैसे ही चले गए।",
      "te": "'ఓ మహాబాహు, ఈ క్షణంలోనే రావణుని సంహరిస్తావు.' అని చెప్పి అగస్త్యుడు వచ్చినట్లే వెళ్ళిపోయాడు.",
      "ta": "'பெருந்தோளனே, இந்தக் கணத்திலேயே ராவணனை வெல்வாய்.' இதைச் சொல்லி அகத்தியர் வந்தவாறே சென்றார்.",
      "kn": "'ಓ ಮಹಾಬಾಹು, ಈ ಕ್ಷಣದಲ್ಲಿಯೇ ರಾವಣನನ್ನು ಸಂಹರಿಸುವೆ.' ಎಂದು ಹೇಳಿ ಅಗಸ್ತ್ಯರು ಬಂದಂತೆಯೇ ತೆರಳಿದರು."}),
]

_SAHASRANAMA = [
    (1,
     "शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम्।\nप्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये॥",
     "Shuklaambara-dharam Vishnum shashi-varnam chatur-bhujam.\nPrasanna-vadanam dhyaayet sarva-vighnopashaantaye.",
     {"en": "Meditate on Vishnu clothed in white, moon-hued, four-armed and serene of face, for the settling of all obstacles.",
      "hi": "श्वेत वस्त्र धारण किए, चंद्रवर्ण, चतुर्भुज और प्रसन्नमुख विष्णु का ध्यान करें, जिससे सब विघ्न शांत हों।",
      "te": "తెల్లని వస్త్రధారి, చంద్రవర్ణుడు, చతుర్భుజుడు, ప్రసన్న ముఖుడైన విష్ణువును ధ్యానించు; సర్వ విఘ్నాలు శాంతిస్తాయి.",
      "ta": "வெண்ணாடை அணிந்த, நிலவு நிறத்த, நான்கு கரங்களுடைய, அமைதி முகத்த விஷ்ணுவை தியானிக்க, தடைகள் அனைத்தும் அமைதியாகும்.",
      "kn": "ಬೆಳ್ಳಗಿನ ವಸ್ತ್ರಧಾರಿ, ಚಂದ್ರವರ್ಣ, ಚತುರ್ಭುಜ, ಪ್ರಸನ್ನ ಮುಖದ ವಿಷ್ಣುವನ್ನು ಧ್ಯಾನಿಸು; ಸರ್ವ ವಿಘ್ನಗಳು ಶಾಂತವಾಗುತ್ತವೆ."}),
    (2,
     "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात्।\nविमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे॥",
     "Yasya smarana-maatrena janma-samsaara-bandhanaat.\nVimuchyate namas tasmai Vishnave prabhavishnave.",
     {"en": "Salutations to that all-capable Vishnu, by whose mere remembrance one is said to be released from the bonds of birth and worldly cycles.",
      "hi": "जिनके स्मरण मात्र से जन्म-संसार के बंधन से मुक्ति होती है, उन प्रभविष्णु विष्णु को नमस्कार।",
      "te": "ఎవరి స్మరణ మాత్రంతోనే జన్మ సంసార బంధాల నుండి విముక్తి కలుగుతుందని చెబుతారో, ఆ ప్రభవిష్ణువైన విష్ణువుకు నమస్కారం.",
      "ta": "யாரை நினைப்பதாலேயே பிறவிச் சுழற்சியின் கட்டுகளிலிருந்து விடுதலை என்பர், அந்த வல்லமை மிக்க விஷ்ணுவுக்கு வணக்கம்.",
      "kn": "ಯಾರ ಸ್ಮರಣೆ ಮಾತ್ರದಿಂದಲೇ ಜನ್ಮ ಸಂಸಾರ ಬಂಧನದಿಂದ ಮುಕ್ತಿ ಎನ್ನುತ್ತಾರೋ, ಆ ಪ್ರಭವಿಷ್ಣು ವಿಷ್ಣುವಿಗೆ ನಮಸ್ಕಾರ."}),
    (3,
     "ॐ विश्वं विष्णुर्वषट्कारो भूतभव्यभवत्प्रभुः।\nभूतकृद्भूतभृद्भावो भूतात्मा भूतभावनः॥",
     "Om vishvam Vishnur vashatkaaro bhoota-bhavya-bhavat-prabhuh.\nBhoota-krid bhoota-bhrid bhaavo bhootaatmaa bhoota-bhaavanah.",
     {"en": "First shloka of names: the universe itself; the all-pervading; the offering; lord of past, future and present; maker, sustainer, being, self and nourisher of all creatures.",
      "hi": "नामों का पहला श्लोक: विश्व, विष्णु, वषट्कार, भूत-भविष्य-वर्तमान के प्रभु, भूतकृत, भूतभृत, भाव, भूतात्मा और भूतभावन।",
      "te": "నామాల మొదటి శ్లోకం: విశ్వం, విష్ణువు, వషట్కారుడు, భూత భవిష్య వర్తమానాలకు ప్రభువు, భూతకృత్, భూతభృత్, భావుడు, భూతాత్మ, భూతభావనుడు.",
      "ta": "பெயர்களின் முதல் சுலோகம்: பிரபஞ்சம், எங்கும் நிறைந்தவன், வஷட்காரன், இறந்த நிகழ் எதிர்காலங்களின் தலைவன், படைப்பவன், தாங்குபவன், இருப்பு, உயிர்களின் ஆன்மா, வளர்ப்பவன்.",
      "kn": "ಹೆಸರುಗಳ ಮೊದಲ ಶ್ಲೋಕ: ವಿಶ್ವ, ವಿಷ್ಣು, ವಷಟ್ಕಾರ, ಭೂತ ಭವಿಷ್ಯ ವರ್ತಮಾನಗಳ ಪ್ರಭು, ಭೂತಕೃತ್, ಭೂತಭೃತ್, ಭಾವ, ಭೂತಾತ್ಮ, ಭೂತಭಾವನ."}),
    (4,
     "पूतात्मा परमात्मा च मुक्तानां परमा गतिः।\nअव्ययः पुरुषः साक्षी क्षेत्रज्ञोऽक्षर एव च॥",
     "Pootaatmaa paramaatmaa cha muktaanaam paramaa gatih.\nAvyayah purushah saakshee kshetragyo akshara eva cha.",
     {"en": "The pure self; the supreme self; the final goal of the liberated; the changeless; the person; the witness; the knower of the field; the imperishable.",
      "hi": "पूतात्मा, परमात्मा, मुक्तों की परम गति, अव्यय, पुरुष, साक्षी, क्षेत्रज्ञ और अक्षर।",
      "te": "పూతాత్మ, పరమాత్మ, ముక్తుల పరమ గతి, అవ్యయుడు, పురుషుడు, సాక్షి, క్షేత్రజ్ఞుడు, అక్షరుడు.",
      "ta": "தூய ஆன்மா, பரமாத்மா, விடுபட்டவரின் இறுதி நிலை, மாறாதவன், புருஷன், சாட்சி, க்ஷேத்ரஜ்ஞன், அழியாதவன்.",
      "kn": "ಪೂತಾತ್ಮ, ಪರಮಾತ್ಮ, ಮುಕ್ತರ ಪರಮ ಗತಿ, ಅವ್ಯಯ, ಪುರುಷ, ಸಾಕ್ಷಿ, ಕ್ಷೇತ್ರಜ್ಞ, ಅಕ್ಷರ."}),
    (5,
     "योगो योगविदां नेता प्रधानपुरुषेश्वरः।\nनारसिंहवपुः श्रीमान् केशवः पुरुषोत्तमः॥",
     "Yogo yoga-vidaam netaa pradhaana-purusheshvarah.\nNaarasimha-vapuh shreemaan Keshavah purushottamah.",
     {"en": "He is union itself; guide of those who know union; lord of nature and spirit; of the Narasimha form; possessor of grace; Keshava; the highest person.",
      "hi": "वे योग हैं, योगविदों के नेता, प्रधान-पुरुष के ईश्वर, नरसिंह रूप, श्रीमान, केशव और पुरुषोत्तम हैं।",
      "te": "ఆయన యోగం, యోగవిదులకు నేత, ప్రధాన పురుషేశ్వరుడు, నారసింహ రూపుడు, శ్రీమంతుడు, కేశవుడు, పురుషోత్తముడు.",
      "ta": "அவர் யோகமே, யோகம் அறிந்தவரின் தலைவன், இயற்கை புருஷனின் ஈசன், நரசிம்ம வடிவினன், திருமால், கேசவன், புருஷோத்தமன்.",
      "kn": "ಅವನು ಯೋಗ, ಯೋಗವಿದರ ನೇತಾರ, ಪ್ರಧಾನ ಪುರುಷೇಶ್ವರ, ನಾರಸಿಂಹ ರೂಪಿ, ಶ್ರೀಮಾನ್, ಕೇಶವ, ಪುರುಷೋತ್ತಮ."}),
    (6,
     "सर्वः शर्वः शिवः स्थाणुर्भूतादिर्निधिरव्ययः।\nसम्भवो भावनो भर्ता प्रभवः प्रभुरीश्वरः॥",
     "Sarvah sharvah shivah sthaanur bhootaadir nidhir avyayah.\nSambhavo bhaavano bhartaa prabhavah prabhur eeshvarah.",
     {"en": "The all; the auspicious remover; the pure; the firm; source of beings; imperishable treasure; the origin; the nurturer; the supporter; the birthplace; the master; the ruler.",
      "hi": "सर्व, शर्व, शिव, स्थाणु, भूतादि, अव्यय निधि, सम्भव, भावन, भर्ता, प्रभव, प्रभु और ईश्वर।",
      "te": "సర్వుడు, శర్వుడు, శివుడు, స్థాణువు, భూతాది, అవ్యయ నిధి, సంభవుడు, భావనుడు, భర్త, ప్రభవుడు, ప్రభువు, ఈశ్వరుడు.",
      "ta": "எல்லாமானவன், சர்வன், தூயவன், நிலையானவன், உயிர்களின் தொடக்கம், அழியாத நிதி, தோற்றம், வளர்ப்பவன், தாங்குபவன், பிறப்பிடம், தலைவன், ஈசன்.",
      "kn": "ಸರ್ವ, ಶರ್ವ, ಶಿವ, ಸ್ಥಾಣು, ಭೂತಾದಿ, ಅವ್ಯಯ ನಿಧಿ, ಸಂಭವ, ಭಾವನ, ಭರ್ತಾ, ಪ್ರಭವ, ಪ್ರಭು, ಈಶ್ವರ."}),
    (7,
     "स्वयम्भूः शम्भुरादित्यः पुष्कराक्षो महास्वनः।\nअनादिनिधनो धाता विधाता धातुरुत्तमः॥",
     "Svayambhooh shambhur aadityah pushkaraaksho mahaasvanah.\nAnaadi-nidhano dhaataa vidhaataa dhaatur uttamah.",
     {"en": "Self-born; source of well-being; the sun; lotus-eyed; of great sound; without beginning or end; upholder; ordainer; the finest support.",
      "hi": "स्वयम्भू, शम्भु, आदित्य, पुष्कराक्ष, महास्वन, अनादिनिधन, धाता, विधाता और धातुओं में उत्तम।",
      "te": "స్వయంభువు, శంభువు, ఆదిత్యుడు, పుష్కరాక్షుడు, మహాస్వనుడు, అనాదినిధనుడు, ధాత, విధాత, ధాతువులలో ఉత్తముడు.",
      "ta": "தானே தோன்றியவன், நலம் தருபவன், ஆதித்யன், தாமரைக் கண்ணன், பெரும் ஒலியன், தொடக்கமும் முடிவும் இல்லாதவன், தாங்குபவன், விதிப்பவன், சிறந்த ஆதாரம்.",
      "kn": "ಸ್ವಯಂಭೂ, ಶಂಭು, ಆದಿತ್ಯ, ಪುಷ್ಕರಾಕ್ಷ, ಮಹಾಸ್ವನ, ಅನಾದಿನಿಧನ, ಧಾತಾ, ವಿಧಾತಾ, ಧಾತುಗಳಲ್ಲಿ ಉತ್ತಮ."}),
    (8,
     "यं ब्रह्मा वरुणेन्द्ररुद्रमरुतः स्तुन्वन्ति दिव्यैः स्तवैः।\nतं सर्वलोकं परमं महान्तं नमामि नित्यं परमेश्वरं हरिम्॥",
     "Yam Brahmaa Varunendra-Rudra-Marutah stunvanti divyaih stavaih.\nTam sarva-lokam paramam mahaantam namaami nityam parameshvaram Harim.",
     {"en": "Whom Brahma, Varuna, Indra, Rudra and the Maruts praise with celestial hymns — to that supreme, vast Hari, present in all worlds, I bow every day.",
      "hi": "जिनकी ब्रह्मा, वरुण, इंद्र, रुद्र और मरुत दिव्य स्तवों से स्तुति करते हैं, उन सर्वलोकव्यापी, परम, महान परमेश्वर हरि को मैं नित्य नमन करता हूँ।",
      "te": "బ్రహ్మ, వరుణ, ఇంద్ర, రుద్ర, మరుత్తులు దివ్య స్తవాలతో స్తుతించే ఆ సర్వలోక వ్యాపి, పరమ, మహాన్ పరమేశ్వరుడైన హరికి నిత్యం నమస్కరిస్తాను.",
      "ta": "பிரம்மா, வருணன், இந்திரன், ருத்திரன், மருத்துக்கள் தெய்வீகப் பாடல்களால் புகழும் அந்த எல்லா உலகிலும் நிறைந்த, மேலான, பெரும் பரமேஸ்வரன் ஹரியை நாளும் வணங்குகிறேன்.",
      "kn": "ಬ್ರಹ್ಮ, ವರುಣ, ಇಂದ್ರ, ರುದ್ರ, ಮರುತ್ತುಗಳು ದಿವ್ಯ ಸ್ತವಗಳಿಂದ ಸ್ತುತಿಸುವ ಆ ಸರ್ವಲೋಕವ್ಯಾಪಿ, ಪರಮ, ಮಹಾನ್ ಪರಮೇಶ್ವರ ಹರಿಗೆ ನಿತ್ಯ ನಮಿಸುತ್ತೇನೆ."}),
]


def _build(prefix, rows):
    return [
        {
            "id": f"{prefix}-{num}",
            "kind": prefix,
            "number": num,
            "devanagari": dev,
            "transliteration": trans,
            "meanings": meanings,
        }
        for (num, dev, trans, meanings) in rows
    ]


ADITYA_HRIDAYAM = _build("aditya", _ADITYA)
VISHNU_SAHASRANAMA = _build("sahasranama", _SAHASRANAMA)

ADITYA_INTRO = {
    "en": "Aditya Hridayam is a hymn to the sun from the Yuddha Kanda of Valmiki's Ramayana, taught by the sage Agastya to Rama before his final battle. Ten representative verses are presented here as cultural and literary heritage; the meanings are simplified study explanations and the benefits described in the verses are traditional belief, not medical or scientific claims.",
    "hi": "आदित्यहृदय वाल्मीकि रामायण के युद्धकांड का सूर्य-स्तोत्र है, जिसे अगस्त्य ऋषि ने अंतिम युद्ध से पूर्व राम को सिखाया। यहाँ दस प्रतिनिधि श्लोक सांस्कृतिक और साहित्यिक विरासत के रूप में दिए गए हैं; अर्थ सरल अध्ययन हेतु हैं और श्लोकों में वर्णित फल परंपरागत विश्वास हैं, चिकित्सा या वैज्ञानिक कथन नहीं।",
    "te": "ఆదిత్య హృదయం వాల్మీకి రామాయణ యుద్ధకాండలోని సూర్య స్తోత్రం; అగస్త్య మహర్షి తుది యుద్ధానికి ముందు రామునికి ఉపదేశించారు. ఇక్కడ పది ప్రాతినిధ్య శ్లోకాలు సాంస్కృతిక, సాహిత్య వారసత్వంగా ఇవ్వబడ్డాయి; అర్థాలు అధ్యయనం కోసం సరళీకృతం, శ్లోకాలలోని ఫలితాలు సంప్రదాయ విశ్వాసాలు, వైద్య లేదా శాస్త్రీయ ప్రకటనలు కాదు.",
    "ta": "ஆதித்ய ஹ்ருதயம் என்பது வால்மீகி ராமாயணத்தின் யுத்த காண்டத்தில் உள்ள சூரிய துதி; இறுதிப் போருக்கு முன் அகத்திய முனிவர் ராமனுக்கு உபதேசித்தார். இங்கு பத்து பிரதிநிதி சுலோகங்கள் கலாச்சார, இலக்கிய பாரம்பரியமாகத் தரப்படுகின்றன; பொருள்கள் எளிய விளக்கங்கள், சுலோகங்களில் கூறப்படும் பலன்கள் பாரம்பரிய நம்பிக்கைகள், மருத்துவ அல்லது அறிவியல் கூற்றுகள் அல்ல.",
    "kn": "ಆದಿತ್ಯ ಹೃದಯ ವಾಲ್ಮೀಕಿ ರಾಮಾಯಣದ ಯುದ್ಧಕಾಂಡದ ಸೂರ್ಯ ಸ್ತೋತ್ರ; ಅಂತಿಮ ಯುದ್ಧದ ಮೊದಲು ಅಗಸ್ತ್ಯ ಮಹರ್ಷಿ ರಾಮನಿಗೆ ಉಪದೇಶಿಸಿದರು. ಇಲ್ಲಿ ಹತ್ತು ಪ್ರಾತಿನಿಧಿಕ ಶ್ಲೋಕಗಳನ್ನು ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು ಸಾಹಿತ್ಯಿಕ ಪರಂಪರೆಯಾಗಿ ನೀಡಲಾಗಿದೆ; ಅರ್ಥಗಳು ಸರಳ ವಿವರಣೆಗಳು, ಶ್ಲೋಕಗಳಲ್ಲಿನ ಫಲಗಳು ಸಾಂಪ್ರದಾಯಿಕ ನಂಬಿಕೆಗಳು, ವೈದ್ಯಕೀಯ ಅಥವಾ ವೈಜ್ಞಾನಿಕ ಹೇಳಿಕೆಗಳಲ್ಲ.",
}

SAHASRANAMA_INTRO = {
    "en": "Vishnu Sahasranama lists a thousand names of Vishnu and comes from the Anushasana Parva of the Mahabharata, where Bhishma recites it to Yudhishthira. The complete text runs to 108 shlokas; eight shlokas — the opening meditation verses and the first name-shlokas — are presented here as a study selection, with simplified meanings and no medical or scientific claims.",
    "hi": "विष्णु सहस्रनाम में विष्णु के एक हजार नाम हैं और यह महाभारत के अनुशासन पर्व से है, जहाँ भीष्म इसे युधिष्ठिर को सुनाते हैं। पूर्ण पाठ 108 श्लोकों का है; यहाँ आठ श्लोक — ध्यान श्लोक और आरंभिक नाम-श्लोक — अध्ययन हेतु चयन के रूप में दिए गए हैं, सरल अर्थों के साथ, किसी चिकित्सा या वैज्ञानिक दावे के बिना।",
    "te": "విష్ణు సహస్రనామంలో విష్ణువు వేయి నామాలు ఉన్నాయి; ఇది మహాభారత అనుశాసన పర్వం నుండి, భీష్ముడు యుధిష్ఠిరునికి చెప్పినది. పూర్ణ పాఠం 108 శ్లోకాలు; ఇక్కడ ఎనిమిది శ్లోకాలు — ధ్యాన శ్లోకాలు, ప్రారంభ నామ శ్లోకాలు — అధ్యయన ఎంపికగా, సరళ అర్థాలతో, ఎటువంటి వైద్య లేదా శాస్త్రీయ వాదనలు లేకుండా ఇవ్వబడ్డాయి.",
    "ta": "விஷ்ணு சஹஸ்ரநாமம் விஷ்ணுவின் ஆயிரம் பெயர்களைக் கொண்டது; இது மகாபாரதத்தின் அனுசாசன பர்வத்திலிருந்து, பீஷ்மர் யுதிஷ்டிரருக்குக் கூறியது. முழுப் பாடம் 108 சுலோகங்கள்; இங்கு எட்டு சுலோகங்கள் — தியான சுலோகங்களும் தொடக்க பெயர் சுலோகங்களும் — படிப்புத் தேர்வாக, எளிய பொருள்களுடன், மருத்துவ அல்லது அறிவியல் கூற்றுகள் இன்றி தரப்படுகின்றன.",
    "kn": "ವಿಷ್ಣು ಸಹಸ್ರನಾಮ ವಿಷ್ಣುವಿನ ಸಹಸ್ರ ನಾಮಗಳನ್ನು ಒಳಗೊಂಡಿದೆ; ಇದು ಮಹಾಭಾರತದ ಅನುಶಾಸನ ಪರ್ವದಿಂದ, ಭೀಷ್ಮರು ಯುಧಿಷ್ಠಿರನಿಗೆ ಹೇಳಿದದ್ದು. ಪೂರ್ಣ ಪಾಠ 108 ಶ್ಲೋಕಗಳು; ಇಲ್ಲಿ ಎಂಟು ಶ್ಲೋಕಗಳು — ಧ್ಯಾನ ಶ್ಲೋಕಗಳು ಮತ್ತು ಆರಂಭಿಕ ನಾಮ ಶ್ಲೋಕಗಳು — ಅಧ್ಯಯನ ಆಯ್ಕೆಯಾಗಿ, ಸರಳ ಅರ್ಥಗಳೊಂದಿಗೆ, ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಅಥವಾ ವೈಜ್ಞಾನಿಕ ಹೇಳಿಕೆಗಳಿಲ್ಲದೆ ನೀಡಲಾಗಿದೆ.",
}
